@echo off
echo Adding MONGODB_URI...
echo mongodb+srv://akhlaquerahman0786_db_user:SmartSplit123@smartsplitcluster.3dpujul.mongodb.net/?appName=SmartSplitCluster | npx vercel env add MONGODB_URI production

echo Adding NODE_ENV...
echo development | npx vercel env add NODE_ENV production

echo Adding GOOGLE_CLIENT_ID...
echo 935634225852-c5742aalk0j3lrs5i1no922ics6ocnlf.apps.googleusercontent.com | npx vercel env add GOOGLE_CLIENT_ID production

echo Adding GOOGLE_CLIENT_SECRET...
echo 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 | npx vercel env add GOOGLE_CLIENT_SECRET production

echo Adding JWT_SECRET...
echo smartsplit_backend_secret_key_2024 | npx vercel env add JWT_SECRET production

echo Adding EMAIL_USER...
echo akhlaquerahman0786@gmail.com | npx vercel env add EMAIL_USER production

echo Adding EMAIL_PASS...
echo xbbpfbttakxlcqfq | npx vercel env add EMAIL_PASS production

echo Adding CLOUDINARY_CLOUD_NAME...
echo dc1qzjxu4 | npx vercel env add CLOUDINARY_CLOUD_NAME production

echo Adding CLOUDINARY_API_KEY...
echo 346355974336281 | npx vercel env add CLOUDINARY_API_KEY production

echo Adding CLOUDINARY_API_SECRET...
echo sAGpC9-SU7KABQttxo9Ye4L-p4s | npx vercel env add CLOUDINARY_API_SECRET production

echo Environment variables added.
